### ISSUE TITLE
oro:platform:update not passing some paramenters to child processes

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/platform#256]
Hi there!
Today while I was trying to upgrade OroCRM, I noticed that some parameters like "timeout" are not being passed to the child process. 

```
 4833 vagrant    20   0  101M  2172  1196 S  0.0  0.1  0:00.40 sshd: vagrant@pts/0
 5250 vagrant    20   0  380M 73012 10168 S  0.0  1.8  0:03.58 php app/console oro:platform:update --env=prod --timeout=999999999999 --force --ansi -vvv --process-isolation
 5216 vagrant    20   0  380M 73096 10196 S  0.0  1.8  0:04.04 /usr/bin/php5 app/console oro:migration:load --force --env=prod
```
I had to run every command manually in order to solve the time-out problem that I was getting on `oro:migration:load`. 

https://github.com/orocrm/platform/blob/8c39d93948cf91d58ece795f432040cf9dab8c32/src/Oro/Bundle/InstallerBundle/Command/PlatformUpdateCommand.php#L60-L71

**Comment by iklymenko** [comment]
Hi Rodolfo,
actually it is not necessary to pass timeout parameter to the child process, when you run command via CommandExecutor with --process-isolation, like it is done in PlatformUpdateCommand if you had set default timeout for this command executor, like it is done here: 
https://github.com/orocrm/platform/blob/8c39d93948cf91d58ece795f432040cf9dab8c32/src/Oro/Bundle/InstallerBundle/Command/PlatformUpdateCommand.php#L58 
Because, CommandExecutor will pass this timeout automatically. 

Check: https://github.com/orocrm/platform/blob/8c39d93948cf91d58ece795f432040cf9dab8c32/src/Oro/Bundle/InstallerBundle/CommandExecutor.php#L105-L110

Could you please provide more details about time-out problem, that you got, so we will be able to more deeply analyze the problem.

**Comment by sergeyz** [comment]
Hi, @rodolfobandeira !

Fixed here https://github.com/orocrm/platform/commit/e7da921a04ebd42f586956f07d9bbd27ceab25f3, please check master or 1.7 release

**Comment by rodolfobandeira** [comment]
Thank you so much!
