### ISSUE TITLE
Failed data audit migration

### ISSUE THREAD

**Issue by ramunasd** [orocrm/platform#285]
Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_3\OroDataAuditBundle fails with error:
`ERROR: Cannot normalize type "datetimetz".`

Version 1.7.3

**Comment by nenadalm** [comment]
Hi. datetimetz is not supported currently. Do you have any reason to use that instead of datetime?

datetime stores dates in UTC because of locale bundle: https://github.com/orocrm/platform/blob/95e7aa8033d39bf6a92aa30770cc918ca5b4da10/src/Oro/Bundle/LocaleBundle/Resources/config/oro/app.yml#L5 so you'll have corret date/time everywhere

in order to support datetimetz audit field
https://github.com/orocrm/platform/blob/95e7aa8033d39bf6a92aa30770cc918ca5b4da10/src/Oro/Bundle/DataAuditBundle/Entity/AuditField.php and the migration would have to be updated

details
=====
the error is here here: https://github.com/orocrm/platform/blob/95e7aa8033d39bf6a92aa30770cc918ca5b4da10/src/Oro/Bundle/DataAuditBundle/Migrations/Schema/v1_3/MigrateAuditFieldQuery.php#L185 because the query doesn't know how to store the data.

Data was stored as array before: https://github.com/orocrm/platform/blob/95e7aa8033d39bf6a92aa30770cc918ca5b4da10/src/Oro/Bundle/DataAuditBundle/Migrations/Schema/v1_0/OroDataAuditBundle.php#L28 (with keys 'old', 'new')

So If you changed datetime, it stored data as ['fieldName' => ['old' => $oldDatetimeInstance, 'new' => $newDataTimeInstance]] (so it didn't matter if the type was date, datetime or datetimetz

But now columns were created for some types (integer, float, date, time, datetime...) and datetimetz is not one of them: https://github.com/orocrm/platform/blob/95e7aa8033d39bf6a92aa30770cc918ca5b4da10/src/Oro/Bundle/DataAuditBundle/Migrations/Schema/v1_3/OroDataAuditBundle.php#L31

Migration works the way that:
1: new columns are created
2: data are copied from array type to new columns
3: old column with data as array is removed (with all data it had)

So the problem is that in step 2 there was data for column of type datetimetz which could not be copied in new schema. Therefore the exception (data cannot be moved to new location and if it would be ignored, data would be lost)

**Comment by turboezh** [comment]
+1
I have same error. 
> ERROR: Cannot normalize type "".

When field is absent in _oro_entity_config_field_.

__\Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_3\MigrateAuditFieldQuery::processRow__ should respect broken data in the _oro_audit_ table.

I faced to 4 problems now:
1) there may be a field in _oro_audit_ that is absent in _oro_audit.data_. In this case $fieldType is false and we have an error like above;
2) Data in _oro_audit.data_ may be totally broken. In this case we haven't any fields and got an error like "Invalid argument supplied for foreach()";
2.1) Also unserialize may fail in convertToPHPValue. In my case I have error "Invalid serialization data for DateTime object in ..."
3) There may be no 'new' or/and 'old' items in the $values. In this case we have "Notice: Undefined index: ... in";
4) In __\Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_3\MigrateAuditFieldQuery::parseValue__ the value may be an object. In this case we have error like "Cannot use object of type ... as array".

**Comment by ramunasd** [comment]
@nenadalm thanks for explanation :)
i understand why this happens, but why platform developers decided to change data audit format?
Problem is doctrine allows to have many custom column types, but data audit bundle supports only few of them. That's not good.

Why platform can't have special data audit events or special audit column type handlers? In that case any custom data type would be supported.

**Comment by nenadalm** [comment]
@ramunasd format of audit was changed because there was requirement to create filters in reports/segments based on history (e.g. show me all contacts having emails changed in the past year - or something more usefull...)

solution to the migration is discussed.

**Comment by ramunasd** [comment]
Btw, datetimetz has big advantage versus simple datetime. First of all, timezone is preserved and can be used by 3rd party tools. Second, datetime gets another form when country switches to summertime. Let's image, yesterday you saw 18:00:00 in data grid, but today 19:00:00 for same record. That confuses a lot.

**Comment by iklymenko** [comment]
Hello guys,
thanks for bringing up this issue!

We definetely understand that fixed list of types reduces the flexibility of DataAudit functionality and this should be fixed. 

We have investigated possible solutions and decided to do the following improvements in DataAudit which should fix described issues:
- Add support of "datetimetz" and "object" field types for DataAudit (also we will investigate what other types may be usefull to support them "from the box")

- Add possibility for developers to extend types with their own, so anyone who uses any types that are not supported will be able to add them. 

- Improve the migration in the way to just copy as is the data of unsupported types, or which could not be converted or recognized for some other reasons; some default format will be used for this purpose. This data will not be used in reporting, we will not display it on a view, but developers will be able to implement migration that will correctly parse such data an store it in the correct way. 

We plan to do these changes in the upcoming release.

**Comment by ramunasd** [comment]
@iklymenko thanks for reply, will wait for next release

**Comment by ramunasd** [comment]
fixed in 1.7.5
