### ISSUE TITLE
OroCRM bundles as stand-alone?

### ISSUE THREAD

**Issue by Mrkisha** [orocrm/platform#382]
Did you guys ever consider making your bundles stand-alone and available on github, rather than all bundles in one package?

**Comment by artml** [comment]
We did, but it is not a highest priority item at the moment.

**Comment by Mrkisha** [comment]
Any timeline?

**Comment by artml** [comment]
None as of yet.

**Comment by StephenOTT** [comment]
@artml you could probably accomplish this using Git Submodules https://git-scm.com/docs/git-submodule and not really have to change any code in your platform repo.  Someone who downloads the platform repo will still get all of your submodules/bundles and it would allow people to download each bundle as a separate git repo if they choose.

**Comment by DimaSoroka** [comment]
@StephenOTT, this is not only about the code distribution. In order to release bundles separately we'll need to validate all the dependencies and test each distribution by itself in order to ensure all features are valid. We have a way to split bundles and components into separate repositories, so no issues there, but we do not have enough resources to maintain standalone distributions.

Do you have any particular bundles in mind?

**Comment by mstaack** [comment]
@DimaSoroka the imap bundle would be really interesting! incl sync logic to a backend like redis or sql

**Comment by Mrkisha** [comment]
@DimaSoroka userbundle as well.

**Comment by dewos** [comment]
#435

**Comment by artml** [comment]
Since we have another newer issue about the same topic, I'm closing this one as a duplicate. Please continue discussion in #435
