### ISSUE TITLE
Add phpunit to composer (dev)

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#413]
I think adding `phpunit` to the list of composer packages for dev makes sense, because the phpunit version can be set by the project and the developer don't has to install phpunit as dependency on the machine.

Running `php -d memory_limit=-1 vendor/bin/phpunit` is easier too, because you don't need to know where phpunit is installed on the CI system => It's always the same path.

Pro:
- easier to use/install
- no dependencies at system
- better version control

Cons:
- another vendor which makes composer slower for require-dev

If you agree, I will create a PR for this one.

Possible versions to install:
- `"phpunit/phpunit": "5.2.x"`
- `"phpunit/phpunit": "@stable"`

PS: `php_codesniffer` can be added too

**Comment by mbessolov** [comment]
Cons:
- it will take additional time to download phpunit with composer on continuous integration servers, vs. using the phpunit included in the pre-built agent image

**Comment by iklymenko** [comment]
Cons:

- in development it is more convenient to use phpunit.phar and configure it in IDE (like in PHPStorm). In this case you will be able to run tests on any projects and using different versions of phpunit without necessity to download it via composer every time.

**Comment by sergeyz** [comment]
its possible to configure phpunit using autoload in PHPStorm https://www.jetbrains.com/help/phpstorm/10.0/enabling-phpunit-support.html?origin=old_help#useAutoload

**Comment by iklymenko** [comment]
@sergeyz yes you can do it, but the main idea is the same. And phar usage is a bit faster.

**Comment by sbani** [comment]
ok thx guys for contribution to this topic. I will close here. You totally convinced me :+1:

**Comment by iklymenko** [comment]
@sbani thanks for your contributions! We appreciate for your interest in our product and all your help!

**Comment by sbani** [comment]
Just want to inform people who read here and have problems running oro tests, that they cannot use the newest `@stable` `phpunit/phpunit`! oro needs `PHPUnit 4.5.0` (for the moment).

There is no info in the docs!

**Comment by sergeyz** [comment]
@sbani for 2.0 release phpunit is in require-dev section now, vesion 5.7 required

**Comment by sbani** [comment]
Thank you @sergeyz for the info.
Can you please explain why you changed it?

**Comment by sergeyz** [comment]
4.8 is EOL now https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.8.0

**Comment by sbani** [comment]
no, I mean why did you choose to add it to the `require-dev` composer section

**Comment by sergeyz** [comment]
I aimed to share all our build configuration and tools with the community and doing it step by step. Check tools configuration [here](https://github.com/orocrm/platform/tree/master/build)

According to composer [docs](https://getcomposer.org/doc/04-schema.md#require-dev)

> require-dev (root-only)#
Lists packages required for developing this package, or running tests, etc

PHPUnit is our development tool

**Comment by sbani** [comment]
Ok I get that. But @mbessolov and @iklymenko once said the total difference if you look up in this issue. Though, I'm totally fine with the end result because that's what I had first suggested too.

Could you provide a write up why you created the build dir and why you added vendors with composer global to travis? Are these things really travis specific only? 
Why do you change the minimum stability? Why do you run `composer update` instead of `composer install`?

Related questions are: Why is travis still missing the functional tests?

I think a complete doc/wiki article about the travis and CI topic would be a great idea because if you write things down and explain it, not only we (as the users) can understand what you are doing here and what is why missing, but you too can see what you need to improve and add it to the roadmap.

I don't find the issue or topic I already talked about these things with @DimaSoroka, but perhaps you can find and use it as a source.

**Comment by sergeyz** [comment]
> Could you provide a write up why you created the build dir and why you added vendors with composer global to Travis? 

Unfortunately, https://github.com/fxpio/composer-asset-plugin doesn't work in local vendors atm. Build dir in the platform repository is a way to share build configuration among all out packages, they require platform in most cases. We plan to release build configuration as a separate package in future.

> Are these things really Travis specific only? Why do you change the minimum stability? 

The similar commands were used on Bambo before Travis. The main reason to do https://github.com/orocrm/platform/blob/master/.travis.yml#L24-L32 in .travis.yml just that all option added there are root-only, works well in application's composer.json  https://github.com/orocrm/platform-application/blob/master/composer.json#L21-L35. Adding options to platform's composer.json just to make CI work looks not so good. But if it helps you with your CI - let's do it.

Why do you run composer update instead of composer install (I know it's the same at this point here)?

We don't store composer.lock in master. As you mentioned, the install will work in the same way, fill be fixed shortly.
Some lines are not required in platform's `.travis.yml` but still there just to make all Travis configuration looks similar. As I mentioned above build package will solve that issues, I will do my best to release it together with platform 2.1.

> Why is travis still missing the functional tests?

The main reason is that we do testing in package repository and application required to run functional tests.

> PS: I (again) can offer you my help with CI. I managed to run functional and unit tests. You just need to email me or ping me at slack.

@sbani, thank you a lot, will contact you shortly, have few questions regards Wercker
