### ISSUE TITLE
ReflectionException Running oro:entity-extend:cache:warmup

### ISSUE THREAD

**Issue by archy-bold** [orocrm/platform#414]
I get and exception when I run `oro:entity-extend:cache:warmup`, or when it's run through migrations with the command, `oro:migration:load`. The error given is as follows:

```
[ReflectionException]
The alias “Oro\Bundle\UserBundle\Model\ExtendUser” for the class “Extend\Entity\EX_OroUserBundle_User” cannot be registered because the class “Oro\Bundle\UserBundle\Model\ExtendUser” is already loaded. This may happen if this class or a derived class is used in EntityConfigDumperExtension or EntityGeneratorExtension.
```

I do have a custom bundle implementation, however I don't think there's a specific change made that would cause this. And, whilst I've extended some entities, I've not extended `User`. Also the entities that were extended were extended a while ago. This problem seems to occur randomly.

I've now experienced this twice. The first time I solved it by reinstalling oro with my custom bundle, which isn't ideal as the migration of the data proved tricky.

I use version 1.8 of Oro.

I've posted a similar thread in [the forum](http://www.orocrm.com/forums/topic/reflectionexception-when-running-migrations).

**Comment by iklymenko** [comment]
@archy-bold , please check reply on the forum: https://www.orocrm.com/forums/topic/reflectionexception-when-running-migrations/#post-17246

**Comment by jorge-marques** [comment]
I'm experiencing a similar issue:

` The alias "Oro\Bundle\OrganizationBundle\Model\ExtendBusinessUnit" for the class "Extend\Entity\EX_OroOrganizationBundle_BusinessUnit" cannot be registered because the class "Oro\Bundle\OrganizationBundle\Model\ExtendBusinessUnit" is already loaded. This may happen if this class or a derived class is used in EntityConfigDumperExtension or EntityGeneratorExtension.  `

The probably only manifests itself when I add an external library to my project: 'sylius/cart-bundle'.

There is an alias conflict introduced by this library, so I added an entity.yml file with this:

    oro_entity:
      entity_alias_exclusions:
          - Sylius\Component\Order\Model\Comment'

This solves the alias conflict error, but now I get the error mentioned above.

**Comment by mkudelya** [comment]
Hi @jorge-marques 

What version of oro platform are you using? When this error appears? Can you explain more detail, which error you had first and second?

**Comment by jorge-marques** [comment]
Hi. I was version 1.10.2. In the meantime I updated to 1.10.4 and it's now working without any problems.
