### ISSUE TITLE
Workflow transition forms do not respect data model

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#427]
When building a transition form (Transition Attributes) in a workflow and you select a related entity such as the Priority Field for a Task (Default setup) few problems come up:

1. Unexpected fields are presented.  The Priority List is a Controlled taxonomy, but I am give the Options of Name, Label, and Order to add to the Form.
2. When you add the Label or Name field, the form is rendered as a text field rather than a drop down.
3. When you modify the Label or name in the text field it modifies it for all tasks... this is understandable given the way it is currently implemented, but it is not the expected result.    

This seems to be a bug or rather a un-implemented feature?
In the following example I changed the label and name to High1 and it changed it in all other records.  Understand why this occurs, but not the expected behaviour.

![screen shot 2016-03-29 at 12 11 33 pm](https://cloud.githubusercontent.com/assets/1994838/14115031/6afc0082-f5a7-11e5-9b25-af76e2263e34.png)
![screen shot 2016-03-29 at 12 11 19 pm](https://cloud.githubusercontent.com/assets/1994838/14115034/6c88faf4-f5a7-11e5-8804-5b6b4c9eae88.png)
![screen shot 2016-03-29 at 12 10 57 pm](https://cloud.githubusercontent.com/assets/1994838/14115037/6e4453f2-f5a7-11e5-95b6-1e5f0090161e.png)

**Comment by yshyshkin** [comment]
Hello, @StephenOTT 

Thank you very much for response! Let me clarify what really happening in workflow when you are working with the relations.

When you are working with some relations in workflow you are allowed to select either relation as is, or any field of this relation - there are big difference between these two approaches.

If you are selecting relation then you are working with relation as is, and you usually see dropdown with the entity selection - i.e. it means that this form will modify field `Priority` of the `Task` entity.
![1](https://cloud.githubusercontent.com/assets/3470882/14116375/b630ecba-f5df-11e5-9b1a-6f0868b9b587.png)
![2](https://cloud.githubusercontent.com/assets/3470882/14116378/bab0aa50-f5df-11e5-8a00-f5c8b05d4bfc.png)

However if you are selecting field of some relation then you work only with this field of the entity, and it will be rendered depends of field type - i.e. it means that this form will modify field `Label` of the `TaskPriority` entity. 
![3](https://cloud.githubusercontent.com/assets/3470882/14116577/b79eb98c-f5e0-11e5-940a-98bf74fc1dd3.png)
![4](https://cloud.githubusercontent.com/assets/3470882/14116580/baca0134-f5e0-11e5-86ec-64813fb680fe.png)

You must understand when and how each of these approaches should be used to avoid unexpected behaviour.

> Unexpected fields are presented. The Priority List is a Controlled taxonomy, but I am give the Options of Name, Label, and Order to add to the Form.

These are fields of `TaskPriority` entity - workflows allow to modify any relation or relation fields you wish, but you should remember whether you are working with relation or with the field of the relation.

> When you add the Label or Name field, the form is rendered as a text field rather than a drop down.

Correct, `Label` is a text field, so it rendered as text input. If you want to see dropdown you should select relation instead of relation field.

> When you modify the Label or name in the text field it modifies it for all tasks... this is understandable given the way it is currently implemented, but it is not the expected result.

Correct again - when you modifying `Label` field in fact you modified label of the dictionary entity, so this change might affect all entities with the current priority. 

In future we are going to convert all such dictionary entities to Enum's, so you will not be able to see fields of these relations.

**Comment by StephenOTT** [comment]
(Face palm)... My brain kept ignoring the priority field and kept looking at the Related Entity priority field.

**Comment by StephenOTT** [comment]
@yshyshkin thanks!
