### ISSUE TITLE
[BUG] DateTime localization bug in datagrid

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#472]
Hi all,

just tested a `datetime` field.
The form field type is `oro_datetime` and in the oro settings is *Germay* and *Europe/Berlin` set.
If I input `06.10.2015 00:00:00` the database is filled with `05.10.2015 22:00:00`. That's UTC and it's correct. 
Opening the (big) form again displays the correct datetime too.

**But in the oro datagrid, the datetime is wrong. (displays UTC time from database)**

Could be related to #468. 

If possible please fix this bug asap and release a bug fix release. This is somehow a critical bug for us and I think for many others too.

**Comment by artml** [comment]
@sbani we're going to have a major release pretty soon (in July) so it's highly unlikely that we'll do a bugfix release for 1.9 branch before that.

Thank you for reporting this bug, we'll do our best to fix it within 1.10 release.

**Comment by sbani** [comment]
major release? 1.10? "pretty soon" in july? you are joking right?

this is a serious bug. the datetimes are wrong in each grid, on every site, whenever somebody is using datetimes.
It means that invoices will be sent at the wrong time, messages go out too early or too late.

I'm sorry, but this is not acceptable and makes me very angry. Especially because there is another task with more bugs for the same topic. Inline edits seem to be very buggy or unfinished.

I know i am not a paying customer, but I am a user of your open source product who can or could contribute frequently. If you don't want to support customers like me, then please say so in your git repo. Please, don't repeat other's mistakes (like nextcloud/owncloud [1](http://www.zdnet.com/article/owncloud-founder-forks-popular-open-source-cloud/)).

It's on you to build a strong community. At the moment you give a damn about it! No infos about your CI stack. Your dev stack in general. Hidden jira task system. Nearly no usage of github (it's getting better). No infos about your "release cycle" or your "versioning system" (you are NOT using semantic versioning).

It's nor against you @artml and neither against anybody in the team personally. In fact, it just seems like you don't want to be a *modern* open source project. Because it means so much more than just displaying code publicly on github!

**Comment by DimaSoroka** [comment]
@sbani, if this issue is critical for your use case feel free to submit contribution and we'll process it or get an enterprise license and we'll support you based on our SLA. 

Our interaction with community is not ideal, but we constantly improving it, i hope you noticed this. Using an open source product means to get tons of features for free and be able to contribute to it, we covering this part. If you need more info - ask, we are open. Release cycle and versioning is covered in our [documentation](https://www.orocrm.com/documentation/index/current/community/release-process).

**Comment by mbessolov** [comment]
Hi @sbani,

I'm sorry that this issues causes so much frustration. We value our community which consists of all users of our products (both enterprise and community editions), partners and developers. We try to share as much as possible with the community and welcome and appreciate all the feedback we receive.

As you may understand sometimes it requires additional time and resources to be involved. And as such we have to prioritize these efforts amongst all other activities - fixing other issues, creating new features, producing new releases. In doing so we have to consider all factors, included how many users are affected and the severity of such impact.

Our approach to release versioning is described in our Community Guide at https://www.orocrm.com/documentation/index/current/community/release-process

We do have an internal task tracking tool because a) not all of our users and partners would feel comfortable sharing all their issues publicly, and b) GitHub is not really a project management and task planning tool that a software development team can use to plan their work and work effectively and efficiently on multiple projects.

We would be glad to share more details about out internal CI stack; it just would mean that some developer has to stop working on a feature or issue and start working on a blog post or documentation article instead. Which, as much as it could be interesting for *some* community developers, would produce little to no value to the *majority* of Oro community. 

We welcome contributions from the community. If you or any community member are willing to provide a fix for this issue - we will gladly review and accept it. Unless it happens, we will allocate resources to fix this issue according to its relative priority amongst other issues scheduled for the next release.

**Comment by sbani** [comment]
Hi @mbessolov, @DimaSoroka,

thanks for your fast answers. I really appreciate that you take care about my concerns.
I know that (human) resources are limited. I know that there are always more tasks than manpower. 

Let me explain some points here. I don't want you to think I just want to blame Oro without any solution or the intention to enhance it.

## JIRA:
In my opinion, all issues which affect the oro core (`oro/platform` and `oro/crm`, ...) need to be stated on Github. Issues, that come from your paying customers will be transferred to Github.
It's because people like me see the process, can discuss about it, or even help you. Non-paying customers won't be surprised by new features anymore and can handle code base changes better.
And the best: It's not more effort for you! You just use the tooling you already own.

## Travis/CI
You implemented the travis CI and you have a good test coverage with nice tests! Travis is for free too, because the project is open source. 
First: Why are there branches with failed builds? It makes no sense! And it downrates your own work.
Second: Why don't you run all tests? It's easy to start the functional tests! (I haven't implemented the selenium tests).

## Community management
Create tasks that are easy, medium or won't be done in the near future by you. You post the issue and it will be done by someone else. If not, there is no loss.
Example Issue: "*Present your CI stack. Implement all tests in travis*" Labels: *Expert*, *RFC*

## Bug handling / Semantic versioning
Bugs kill a product! Bugs are bad and very expensive - for everybody! You product claims to be stable. Let me quote [sever.com](http://semver.org/#how-do-i-know-when-to-release-100):
> If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

Ok then. Let's check your UPGRADE files. There are so freaking many changes most upgrades since 1.x. You shouldn't call some minor! From 1.8 to 1.9, I needed to upgrade our code base for two weeks without changing a single feature set - and our code base is not very big. But the minor-major-thing is always difficult!
Oro is under rapid development. That's brilliant because we see so many features, but if you say that the platform is stable, you should care about BC and you need to make sure that the product is bug free, because people rely on it. 
A good example is the inline edit feature (and bug from this issue): The feature is not even close to stable! There are so many bugs because of localization.

Let's talk about the bug fix releases:
The [upgrade](https://github.com/orocrm/platform/blob/1.9.3/UPGRADE-1.9.1.md) from 1.9.0 to 1.9.1 is a good example because you changed the *public API*. The `oro/platform` is used as a framework and when you change the codebase people cannot rely on you as a vendor. 
Question: Do you version for end users or do you version for developers?

**New features are good, but if you are stable, bug free is most important.**

Let me ask a question again:
What would you say if Doctrine releases a bug fix release which breaks the code of 5% users and they say that they will first work on other features for about a month because 5% are not relevant? Do you think this product is *stable*?

Take your time, discuss it or email me. I would love to discuss it from face2face, but I sit in Germany as you know... Next conference... 👍 

Best regards

**Comment by DimaSoroka** [comment]
Thanks @sbani, your feedback is very clear, we love to have this kind of conversations.

GitHub is very good code collaboration tool, but unfortunately issue tracking capabilities are not there yet and we can't retire Jira in favor of GitHub. Majority of new features are covered in our [roadmap ](https://www.orocrm.com/orocrm-and-platform-roadmap) so no surprises to community on what is coming.

In order to handle community requests on GitHub in better way, we decided to classify all issues in three groups: [feedback needed](https://github.com/orocrm/platform/labels/feedback%20needed), [open for contribution](https://github.com/orocrm/platform/labels/open%20for%20contribution) and [scheduled for implementation](https://github.com/orocrm/platform/labels/scheduled%20for%20implementation). This will allow to understand when and how particular issue will be handled and open areas for contribution. 

Travis setup is coming, we are almost done with migration of our private repositories to travis and once this will be complete we will update public configurations as well.

In terms of semantic versioning, we can't commit to full backward compatibility with minor version releases yet, but this is definitely where we would like to be soon. This is defined in our [documentation](https://www.orocrm.com/documentation/index/current/community/release-process#oro-product-versions), and we working hard to make upgrade process less painful. With patch (bug fix) releases we maintain full backward compatibility (exceptions like [1.9.1](https://github.com/orocrm/platform/blob/1.9/UPGRADE-1.9.1.md) will not happen anymore).

Thanks again for helping us to make our product better.

**Comment by artml** [comment]
Fixed within 1.10 release
