### ISSUE TITLE
Unable to install platform on Symfony 2.8 Standard Edition

### ISSUE THREAD

**Issue by ste93cry** [orocrm/platform#531]
While trying to install the platform version `~1.10` in a project based on `Symfony 2.8 Standard Edition` an error occurs. The only version tagged on packagist for SensioDistributionBundle is `5.0`, which is required in the `composer.json` of Symfony.

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - oro/platform 1.10.4 requires sensio/distribution-bundle 4.0.\* -> satisfiable by sensio/distribution-bundle[4.0.x-dev, v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9] but these conflict with your requirements or minimum-stability.
>     - oro/platform 1.10.3 requires sensio/distribution-bundle 4.0.\* -> satisfiable by sensio/distribution-bundle[4.0.x-dev, v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9] but these conflict with your requirements or minimum-stability.
>     - oro/platform 1.10.2 requires sensio/distribution-bundle 4.0.\* -> satisfiable by sensio/distribution-bundle[4.0.x-dev, v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9] but these conflict with your requirements or minimum-stability.
>     - oro/platform 1.10.1 requires sensio/distribution-bundle 4.0.\* -> satisfiable by sensio/distribution-bundle[4.0.x-dev, v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9] but these conflict with your requirements or minimum-stability.
>     - oro/platform 1.10.0 requires sensio/distribution-bundle 4.0.\* -> satisfiable by sensio/distribution-bundle[4.0.x-dev, v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9] but these conflict with your requirements or minimum-stability.
>     - Installation request for oro/platform ~1.10 -> satisfiable by oro/platform[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4].

**Comment by mbessolov** [comment]
@ste93cry what is the minimum-stability defined in your application's composer.json?

**Comment by ste93cry** [comment]
There is no minimum-stability specified. You can find the `composer.json` file [here](https://github.com/symfony/symfony-standard/blob/2.8/composer.json)

**Comment by ste93cry** [comment]
Could we relax a bit the composer dependencies? Almost all constraints declared in the `composer.json` of the platform are specific versions of a library, however this means that users trying to use the platform standalone are obliged to use the versions you defined, nothig older nothing newer, even if they are compatible. I tried running tests with a few dependencies updated on Windows, and the results for me are great: there are a few skipped tests 19 failed tests. Almost all of the failed tests comes from the Layout component and bundle), but nothing that seems related to the updated versions of the library because tests were failing even before (at least on my PC). Also, most of the failing tests is just because of directory separators (`/` vs `\`)

**Comment by DimaSoroka** [comment]
@ste93cry we can update dependencies by request, but our experience of using .* style versions wasn't good as even patch version releases of some components were braking application. Feel free to submit a PR with updated package dependencies if you have issues with versions defined in composer.json.

**Comment by ste93cry** [comment]
I would be happy to submit a PR, but this would solve the issue only temporarily. I perfectly understand that given the size of the platform, having relaxed constraints can cause breaks but libraries should follow the semver conventions, so BC breaks should not be possible if the major version is not changed. A lot of other projects use such related constraints, and I don't think they have much problems. Also, even if I update the dependencies to their latest version and fix again that exact version as a dependency, maybe tomorrow a new version of that library that fixes some bugs is released and we cannot use it without updating again the `composer.json`. Also, if you continue to use fixed constraints then it can take a long time to update them again, meaning that some dependencies are a lot of versions old (take for example KnpMenu, which is at `2.0.0-alpha2` while there is `2.2`. Now, this is a case where upgrading breaks the platform, but you're using a dev version (which is even old)

**Comment by sergeyz** [comment]
"twig/twig": "~1.26" is too wide, so in patch version update of platform might be minor vendor update and that is semver violation, see https://github.com/orocrm/crm/issues/210 for more details

cc @sbani

**Comment by ste93cry** [comment]
I'm not really sure I fully understand the issue about the semver violation. I'm a newbie on the topic, so please be patient with me, but according to [semver ](http://semver.org/) the version number is defined as:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

So, even if `~1.26` could install a new minor vendor update, this shouldn't break the platform is that library is following semver too because the only thing that it could so is add new functionality in a backwards-compatible manner. Anyway, maybe we can restrict the constraints to something like `~1.26.x`? The only thing I'm trying to discourage if having fixed constraints that makes impossible to end-users to use their own vendor constraints, even if they know they are compatible with yours

**Comment by sergeyz** [comment]
It might. Lets check case with hwi/oauth-bundle update

* [~0.3 is required in composer.json](https://github.com/orocrm/platform/blob/master/composer.json#L71)

* 0.4.2 locked in composer.lock
```
$ composer show | grep hwi
hwi/oauth-bundle                         0.4.2           Support for authenticating users using both OAuth1.0a and OAuth2 in Symfony2.
```

* 0.5 [released](https://github.com/hwi/HWIOAuthBundle/releases/tag/0.5.0) and [matches ~0.3 constraints](https://semver.mwl.be/#?package=hwi%2Foauth-bundle&version=~0.3&minimum-stability=stable)

Same time [0.4 release required changes in code](https://github.com/hwi/HWIOAuthBundle/releases/tag/0.4.0)

> Added: configuration parameter firewall_name (will be removed in next major version) renamed to firewall_names to support multiple firewalls

And [without platform support it becomes broken](https://github.com/orocrm/platform/commit/4cab62f9dc9e2ac025f35507e9048af01448e5f2)

Thats why with `hwi/oauth-bundle:~0.3` constraint platform's PATCH release might require manual work from your side and that is not `backwards-compatible bug fixes`

**Comment by ste93cry** [comment]
You're correct in saying that updating that library broke your application, but it should not had. Infact, looking at the code they reverted the change to be BC-compatible in [`0.4.0`](https://github.com/hwi/HWIOAuthBundle/commit/65127181c2fc02467f9e293a59efb611d31a420d). Unfortunately, in 0.5 they removed that "BC-compatible layer" and imho, again, they should not had to because according to the definition of semver posted before only major version changes should introduce BC breaks, and 0.5 is not a major version (according to the specs). At least, this is what I understand from that website. If I'm wrong, sorry.

**Comment by sbani** [comment]
Just my 2cents:

**Minor versions are not safe. Only patch versions _should_ be safe.**

You see a perfect bad example here in `oro/platform` (`UPGRADE-1.10.1.md` - More details here orocrm/crm#210)

Because you cannot trust vendors like the orocrm team, who have problems with semver, you should **always fixate versions for production** and that's why the `composer.lock` was introduced.

>  we can update dependencies by request, but our experience of using .* style versions wasn't good as even patch version releases of some components were braking application.
He's totally correct. But it's a matter of trust. I trust the symfony team and therefore always use variable patch versions for their libs to benefit from bug fixes etc.

I think you should always try use variable patch versions, because you benefit from security fixes with a minimum risk as far as the vendor is competent.
If there are problems with a patch version, you can update your own `composer.json` as fast as possible with a fixed version. But you have to be fast.

@sergeyz:
Why do you seem to understand semver and composer but still have `"hwi/oauth-bundle": "~0.3"` in the composer.json in master? You seem to know that it will break the application **but still have it in your vendors list?
Just to make sure: The `composer.lock` in `oro/platform-application` is no excuse, because every user who needs a new vendor has to rely on the `composer.json` files from his vendors because the `composer.lock` will be overwritten! 

Back to your request @ste93cry
Because of the vendors from `oro/platform` and Symfony 2.8 Standard Edition are simply not compatible and if the oro team would relax the vendors, the oro platform is highly unstable for some users.

I recommend to you the following reads:
http://semver.org/
https://getcomposer.org/doc/articles/versions.md
https://semver.mwl.be/#?package=hwi%2Foauth-bundle&version=~0.3&minimum-stability=stable

Hope I can help you with it

**Comment by sergeyz** [comment]
@ste93cry @sbani 

Back here with 2.0 release. All PHP vendors were allowed to update patch versions only https://github.com/orocrm/platform/blob/master/composer.json#L19-L110. We tried to update as much as possible.

`oro/redis-config` is a specific case, not locked because we are not going to break things and it's not enabled without configuration

JS vendors locked to specific versions (a lot of issues in patch releases)

**Comment by ste93cry** [comment]
This is great, although at least Symfony should be allowed to update minor releases too because the compatibility is granted by their [Backwards Compatibility Promise](http://symfony.com/doc/current/contributing/code/bc.html). It's true that sometimes they made BC breaks, but they reverted all of the changes as soon as they discovered them. In reality, while agreeing with @sbani that indeed many third-parties vendors don't follow SEMVER or don't know how to do it, there are a few other big projects like Doctrine that usually don't break BC, so they should too be allowed to update imho.

**Comment by mkudelya** [comment]
@sbani @ste93cry 

Do you still have any questions or can I close this issue?

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
