### ISSUE TITLE
Required parameter in the constructor

### ISSUE THREAD

**Issue by kamilwojciuk** [orocrm/platform#532]
Hi, i found a bug in the actions: HOST/email/emailtemplate/create

Catchable Fatal Error: Argument 1 passed to Oro\Bundle\EmailBundle\Form\DataTransformer\EmailTemplateTransformer::__construct() must be an instance of Oro\Bundle\FormBundle\Form\DataTransformer\SanitizeHTMLTransformer, none given, called in /var/www/html/zid/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Form/Type/EmailTemplateRichTextType.php on line 19 and defined in /var/www/html/zid/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Form/DataTransformer/EmailTemplateTransformer.php on line 21

**Comment by sergeyz** [comment]
Hi, @kamilwojciuk, thank you for report!

@artml looks like same as https://github.com/orocrm/crm/issues/218

**Comment by geoffroycochard** [comment]
Hi,
In 1.10 branch, [EmailTemplateTransformer waiting for SanitizeHTMLTransformer](https://github.com/orocrm/platform/blob/1.10.4/src/Oro/Bundle/EmailBundle/Form/DataTransformer/EmailTemplateTransformer.php) construct argument (against master branch) otherwise EmailTemplateRichTextType not instantiate it since [1.10.3](https://github.com/orocrm/platform/blob/1.10.3/src/Oro/Bundle/EmailBundle/Form/Type/EmailTemplateRichTextType.php)

**Comment by geoffroycochard** [comment]
i've upgrade two class (EmailTemplateRichTextType, EmailTemplateTransformer) to their master branch version..
No more errors but emails generated don't transform entity data (all dynamic data "N/A")

**Comment by geoffroycochard** [comment]
Hi,
I've manually upgrade this two files 

- [EmailTemplateRichTextType](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EmailBundle/Form/Type/EmailTemplateRichTextType.php)
- [EmailTemplateTransformer](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EmailBundle/Form/DataTransformer/EmailTemplateTransformer.php)

It's a temp solution...

**Comment by mkudelya** [comment]
The issue was fixed. I'm closing it.
