### ISSUE TITLE
Web Installer JS Errors 

### ISSUE THREAD

**Issue by duffner** [orocrm/platform#562]
When all prerequisites of installation have been successful, the next button is greyed out, yet still clickable.  The follow JS errors are thrown in the console..  Google Chrome Mac OSX 

Installation as followed here: https://github.com/orocrm/platform-application

```jquery-2.0.3.min.js:1 Uncaught SyntaxError: Unexpected token <
bundles/oroinstaller/js/javascript.js:2 Uncaught ReferenceError: $ is not defined(…)(anonymous function) @ bundles/oroinstaller/js/javascript.js:2
install.php:15 Uncaught ReferenceError: $ is not defined(…)(anonymous function) @ install.php:15```



<img width="2045" alt="screen shot 2016-11-01 at 3 27 56 pm" src="https://cloud.githubusercontent.com/assets/7387019/19906194/cf38280a-a047-11e6-9b9c-fbe044f07d27.png">

**Comment by Grygir** [comment]
Hi @duffner, 

What version of platform-application do you install? Is it dev-master or specific release version?

**Comment by duffner** [comment]
@Grygir, this is master branch of the platform application.  I did have success yesterday when I ran the CLI install differently from your instructions, however never could get the Web Install tool to work correctly.    My success in the CLI install was by running ```php app/console oro:install``` instead of ```php app/console oro:install --env prod```  I'm not sure what the difference is there as I haven't looked yet.

**Comment by Grygir** [comment]
I just checked installation over HTTP, it went fine.
I see from the screen you've provided, there is incorrect reference on jquery lib.
In the template https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/InstallerBundle/Resources/views/layout.html.twig#L12

But in your screen it is `jquery-2.0.3.min.js`. Guess, you have stale twig templates cache.

Clear application cache for prod and dev environment before installation.

That's why you could not install over console for prod env
`php app/console oro:install --env prod`

**Comment by duffner** [comment]
Understood, I will give this a try and provide my feedback.  Can you provide me the proper way to clear environment cache, or a link to the documentation?

**Comment by Grygir** [comment]
```bash
php app/console cache:clear --env=dev
php app/console cache:clear --env=prod
```

**Comment by duffner** [comment]
This appears to have corrected my issue, I appreciate your insight.  Thank you - You can close this ticket
